# This is a placeholder so actions won't default to a getting started page

name: Placeholder

on: 
  push:
    branches: main

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
